import 'package:floor/floor.dart';
import 'package:sps/local_database/tables/local_database_tables.dart';
import 'package:sps/models/support_package.dart';
import 'package:json_annotation/json_annotation.dart';

part 'receive_package_entity.g.dart';

@Entity(tableName: LocalDataBase.patient_support_package_table)
@JsonSerializable()
class ReceivePackageEntity {
  @PrimaryKey(autoGenerate: true)
  final int? id;
  final int? remoteId;
  final int localPatientSupportMonthId;
  final int? remotePatientPackageId;
  final int? localPatientPackageId;
  final int amount;
  final String patientPackageName;
  final int? reimbursementMonth;
  final String? reimbursementMonthYear;

  ReceivePackageEntity({
    this.id,
    this.remoteId,
    required this.amount,
    required this.localPatientSupportMonthId,
    this.remotePatientPackageId,
    this.localPatientPackageId,
    required this.patientPackageName,
    required this.reimbursementMonth,
    required this.reimbursementMonthYear,
  });

  factory ReceivePackageEntity.mapRemoteReceivePackageToLocalEntity(
      SupportPackage remoteReceivePackage, int localPatientSupportMonthId) {
    return ReceivePackageEntity(
      id: null, // Auto-generated by the database
      localPatientSupportMonthId: localPatientSupportMonthId,
      remotePatientPackageId: remoteReceivePackage.patientPackageId,
      amount: remoteReceivePackage.amount,
      patientPackageName: remoteReceivePackage.patientPackageName,
      reimbursementMonth: remoteReceivePackage.reimbursementMonth,
      reimbursementMonthYear: remoteReceivePackage.reimbursementMonthYear,
    );
  }

  factory ReceivePackageEntity.fromJson(Map<String, dynamic> json) =>
      _$ReceivePackageEntityFromJson(json);

  Map<String, dynamic> toJson() => {
        'id': id,
        'remote_id': remoteId,
        'local_patient_support_month_id': localPatientSupportMonthId,
        'remote_patient_package_id': remotePatientPackageId,
        'local_patient_package_id': localPatientPackageId,
        'amount': amount,
        'patient_package_name': patientPackageName,
        'reimbursement_month': reimbursementMonth,
        'reimbursement_month_year': reimbursementMonthYear,
      };
}
