import 'package:floor/floor.dart';
import 'package:sps/local_database/tables/local_database_tables.dart';
import 'package:sps/models/support_package.dart';

@Entity(tableName: LocalDataBase.patient_support_package_table)
class ReceivePackageEntity {
  @PrimaryKey(autoGenerate: true)
  final int? id;
  final int? remoteId;
  final int localPatientSupportMonthId; 
  final int? remotePatientPackageId;
  final int? localPatientPackageId;
  final int amount;
  final String patientPackageName; 
  final int? reimbursementMonth;
  final String?
      reimbursementMonthYear; 

  ReceivePackageEntity({
    this.id,
    this.remoteId,
    required this.amount,
    required this.localPatientSupportMonthId,
    this.remotePatientPackageId,
    this.localPatientPackageId,
    required this.patientPackageName,
    required this.reimbursementMonth,
    required this.reimbursementMonthYear,
  });

  factory ReceivePackageEntity.mapRemoteReceivePackageToLocalEntity(
      SupportPackage remoteReceivePackage, int localPatientSupportMonthId) {
    return ReceivePackageEntity(
      id: null, // Auto-generated by the database
      localPatientSupportMonthId: localPatientSupportMonthId,
      remotePatientPackageId: remoteReceivePackage.patientPackageId,
      amount: remoteReceivePackage.amount,
      patientPackageName: remoteReceivePackage.patientPackageName,
      reimbursementMonth: remoteReceivePackage.reimbursementMonth,
      reimbursementMonthYear: remoteReceivePackage.reimbursementMonthYear,
    );
  }
}
