import 'package:floor/floor.dart';
import 'package:sps/local_database/tables/local_database_tables.dart';
import 'package:sps/models/remote_township.dart';

@Entity(tableName: LocalDataBase.user_township_table)
class UserTownshipEntity {
  @primaryKey
  final int? id;
  final int remoteId;

  final String name;

  final String abbreviation;

  UserTownshipEntity({
    this.id,
    required this.remoteId,
    required this.name,
    required this.abbreviation,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'abbreviation': abbreviation,
    };
  }

  factory UserTownshipEntity.fromMap(Map<String, dynamic> map) {
    return UserTownshipEntity(
      id: map['id'],
      remoteId: map['remoteId'],
      name: map['name'],
      abbreviation: map['abbreviation'],
    );
  }
  factory UserTownshipEntity.mapTownshipToUserTownshipEntity(
      Township township) {
    return UserTownshipEntity(
      id: null, // Auto-generated by the database
      remoteId: township.id,
      name: township.name,
      abbreviation: township.abbreviation,
    );
  }
}
